module.exports = {
  plugins: ['stylelint-order'],
  customSyntax: 'postcss-styled-syntax',
  files: ['**/*styled.ts'],
  rules: {
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-order': [
      {
        groupName: 'position',
        emptyLineBefore: 'always',
        noEmptyLineBetween: true,
        properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
      },
      {
        groupName: 'layout',
        emptyLineBefore: 'always',
        noEmptyLineBetween: true,
        properties: [
          'display',
          'grid',
          'grid-template-columns',
          'grid-template-rows',
          'grid-template-areas',
          'grid-template',
          'gap',
          'grid-gap',
          'row-gap',
          'column-gap',
          'grid-column-gap',
          'grid-row-gap',
          'grid-auto-columns',
          'grid-auto-rows',
          'grid-auto-flow',
          'grid-column-start',
          'grid-column-end',
          'grid-row-start',
          'grid-row-end',
          'grid-column',
          'grid-row',
          'flex',
          'flex-direction',
          'flex-flow',
          'flex-wrap',
          'place-content',
          'place-items',
          'place-self',
          'align-content',
          'align-items',
          'align-self',
          'justify-content',
          'justify-items',
          'justify-self',
          'flex-grow',
          'flex-shrink',
          'order',
          'float',
          'clear',
          'width',
          'min-width',
          'max-width',
          'height',
          'min-height',
          'max-height',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
        ],
      },
      {
        groupName: 'other',
        emptyLineBefore: 'always',
        noEmptyLineBetween: true,
        properties: [
          'content',
          'color',
          'fill',
          'stroke',
          'background',
          'background-clip',
          'background-color',
          'background-position',
          'background-repeat',
          'background-size',
          'border',
          'border-bottom',
          'border-bottom-color',
          'border-bottom-style',
          'border-bottom-width',
          'border-color',
          'border-left',
          'border-left-color',
          'border-left-style',
          'border-left-width',
          'border-right',
          'border-right-color',
          'border-right-style',
          'border-right-width',
          'border-style',
          'border-top',
          'border-top-color',
          'border-top-style',
          'border-top-width',
          'border-width',
          'border-radius',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-bottom-left-radius',
          'border-bottom-right-radius',
          'box-sizing',
          'font',
          'font-family',
          'font-size',
          'font-weight',
          'line-height',
          'letter-spacing',
          'font-feature-settings',
          'list-style',
          'cursor',
          'opacity',
          'outline',
          'filter',
          'pointer-events',
          'object-fit',
          'overflow',
          'overflow-x',
          'overflow-y',
          'overflow-wrap',
          'text-overflow',
          'white-space',
          'word-break',
          'word-wrap',
          'transition',
          'visibility',
          'hyphens',
          'text-align',
          'text-transform',
          'text-decoration',
          'text-underline-offset',
          'text-indent',
          'text-justify',
          'text-shadow',
          'writing-mode',
          'box-shadow',
          'transform',
          'zoom',
          'scroll-snap-align',
          '-webkit-box-shadow',
          '-webkit-text-fill-color',
          '-webkit-font-smoothing',
          '-moz-osx-font-smoothing',
          '-webkit-appearance',
          'animation',
          'animation-name',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',
          'animation-fill-mode',
          'animation-play-state',
          'resize',
          'page-break-after',
          'page-break-before',
          'page-break-inside',
          'mix-blend-mode',
        ],
      },
    ],
  },
};
